config/routes.rb
Likesdiary::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
	
	devise_scope :user do
		get "/login" => "devise/sessions#new"
		get "/logout" => "devise/sessions#destroy"
		get "/register" => "devise/registrations#new"
	end

	match 'products/recentupdate' , :to => 'products#recentupdate'
	match 'products/friendsupdate' , :to => 'products#friendsupdate'
	match 'products/toplist' , :to => 'products#toplist'
	match 'products/commentlist' , :to => 'products#commentlist'
	match 'products/add_image' , :to => 'products#add_image'
	match 'users/likeit' , :to=>'products#likeit'
	
	resources :deals do
		resources :dealcomments
	end
	resources :maingroups
	resources :categories
	resources :subgroups
	resources :ratingcategories
	resources :products do
		resources :associations
		resources :recentupdate
		resources :productcomments, :except => [:index, :show]
		resources :reviews, :except => [:index, :show]
		member do
			get :users
			get :productcomments
			get :reviews
			get :recentupdate			
		end
	end	

	match 'users/followedBy' , :to=> 'users#followedBy'
	
	resources :users do
		member do
			get :following, :followers, :requests ,:requestAct
		end
	end
  resources :user_sessions
	resources :cities
	resources :merchants do
		resources :merchantcomments
	end
	
	resources :relationships, :only => [:create, :destroy]
	resources :ratings, :only => [:create, :update]
	resources :product_likes, :only => [:create, :destroy]
	resources :merchant_likes, :only => [:create, :destroy]
	resources :deal_likes, :only => [:create, :destroy]

  get "user_sessions/new"

  get "users/new"
  
	match '/verify_user', :to => 'pages#verify_user'
	match '/logUser' , :to => 'pages#logUser'
	match '/contact', :to => 'pages#contact'
	match '/about', :to => 'pages#about'
	match 'signup', :to => 'users#new'  
	match 'login' => 'user_sessions#new', :as => :login
	match 'logout' => 'user_sessions#destroy', :as => :logout
	match 'cheapsdiary' => 'deals#currentdeal'
	match 'search' => 'pages#search'
	match 'newsfeed', :to => 'users#newsfeed'	
	
	root :to => 'pages#home'

end

app/models/maingroup.rb
class Maingroup < ActiveRecord::Base
	has_many :categories, :dependent => :destroy
	has_many :ratingcategories, :dependent => :destroy
	
	validates :name, :presence => true, :length => {:within => 2..50}

end

app/controllers/maingroups_controller.rb
class MaingroupsController < ApplicationController
	layout 'profile'
	before_filter :is_admin?, :except => [:index, :show]
  def new
		@title = "Create a new Maingroup"
		@maingroup = Maingroup.new
  end

  def index
		@maingroups_all = Maingroup.all
		@maingroups = @maingroups_all.group_by { |t| t.variety }
  end

  def show
		@maingroup = Maingroup.find(params[:id])
		@categories = @maingroup.categories
		redirect_to @categories[0]
  end

  def edit
		@maingroup = Maingroup.find(params[:id])
  end
	
	def create 
		@maingroup = Maingroup.new(params[:maingroup])
		if @maingroup.save
			redirect_to @maingroup
			flash[:success] = 'Deal was successfully created'
		else
			render :action => :new
		end
	end
	
	def update
		@maingroup = Maingroup.find(params[:id])
		if @maingroup.update_attributes(params[:maingroup])
			redirect_to @maingroup
			flash[:success] = 'Maingroup updated'
		else
			render :action => :edit
		end
	end
	
	def destroy
		@maingroup = Maingroup.find(params[:id])
		@maingroup.destroy
		flash[:success] = 'Maingroup deleted'
		redirect_to(maingroups_path)
	end

end

app/helpers/maingroups_helper.rb
module MaingroupsHelper
end

app/views/maingroups/_form.erb
<div>
  <%= form.label :name %>
  <%= form.text_field :name %>
</div>
<div>
	<%= form.label :variety %>
	<%= form.select( :variety, [["1", 1], ["2", 2], ["3", 3], ["4", 4], ["5", 5], ["6", 6]]) %>
</div>

app/views/maingroups/_maingroup.html.erb
Maingroup
<%= maingroup.name %>
<% if isadmin? %>
<%= link_to "Edit", edit_maingroup_path(maingroup) %>
<%= link_to 'Show', maingroup %>
<%= link_to 'Destroy', maingroup, :confirm => 'Are you sure?', :method => :delete %>
<% end %>
<br/>

app/views/maingroups/_top.html.erb
<%= render @maingroups1 %>
<br/>category 2<br/>
<%= render @maingroups2 %>
<br/>category 3<br/>
<%= render @maingroups3 %>
<br/>category 4<br/>
<%= render @maingroups4 %>
<br/>category 5<br/>
<%= render @maingroups5 %>
<br/>category 6<br/>
<%= render @maingroups6 %>

app/views/maingroups/edit.html.erb
<br/><br/><br/>
<h1>Editing maingroup </h1>

<%= form_for @maingroup do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <%= render :partial => 'form', :object => f %>
  <%= f.submit "Update main group!!!" %>
<% end %>

<%= link_to 'Show', @maingroup %> |
<%= link_to 'Back', maingroups_path %>

app/views/maingroups/index.html.erb
<%= render 'shared/top' %>
<br/><br/>
<% if isadmin? %>
<%= link_to "New Maingroup", new_maingroup_path %>
<% end %>

app/views/maingroups/new.html.erb
<h1>Create a new maingroup</h1>

<%= form_for @maingroup, :url => maingroups_path do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <%= render :partial => 'form', :object => f %>
  <%= f.submit "Create Maingroup!!!" %>
<% end %>

app/views/maingroups/show.html.erb
<%= render 'shared/top' %>
<br/><br/><br/><br/>
<div>
	<b>Name </b>
	<%= @maingroup.name %>
	<%= @maingroup.variety %>
</div>
<% unless @categories.empty? %>
	<ul class="users">
		<%= render @categories %>
	</ul>
<% end %>

Rating categories<br/><br/>
<% if isadmin? %>
	<%= render :partial => "ratingcategories/ratingcategory",
           :collection => @ratingcategories %>
<% end %>