config/routes.rb
Likesdiary::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
	
	devise_scope :user do
		get "/login" => "devise/sessions#new"
		get "/logout" => "devise/sessions#destroy"
		get "/register" => "devise/registrations#new"
	end

	match 'products/recentupdate' , :to => 'products#recentupdate'
	match 'products/friendsupdate' , :to => 'products#friendsupdate'
	match 'products/toplist' , :to => 'products#toplist'
	match 'products/commentlist' , :to => 'products#commentlist'
	match 'products/add_image' , :to => 'products#add_image'
	match 'users/likeit' , :to=>'products#likeit'
	
	resources :deals do
		resources :dealcomments
	end
	resources :maingroups
	resources :categories
	resources :subgroups
	resources :ratingcategories
	resources :products do
		resources :associations
		resources :recentupdate
		resources :productcomments, :except => [:index, :show]
		resources :reviews, :except => [:index, :show]
		member do
			get :users
			get :productcomments
			get :reviews
			get :recentupdate			
		end
	end	

	match 'users/followedBy' , :to=> 'users#followedBy'
	
	resources :users do
		member do
			get :following, :followers, :requests ,:requestAct
		end
	end
  resources :user_sessions
	resources :cities
	resources :merchants do
		resources :merchantcomments
	end
	
	resources :relationships, :only => [:create, :destroy]
	resources :ratings, :only => [:create, :update]
	resources :product_likes, :only => [:create, :destroy]
	resources :merchant_likes, :only => [:create, :destroy]
	resources :deal_likes, :only => [:create, :destroy]

  get "user_sessions/new"

  get "users/new"
  
	match '/verify_user', :to => 'pages#verify_user'
	match '/logUser' , :to => 'pages#logUser'
	match '/contact', :to => 'pages#contact'
	match '/about', :to => 'pages#about'
	match 'signup', :to => 'users#new'  
	match 'login' => 'user_sessions#new', :as => :login
	match 'logout' => 'user_sessions#destroy', :as => :logout
	match 'cheapsdiary' => 'deals#currentdeal'
	match 'search' => 'pages#search'
	match 'newsfeed', :to => 'users#newsfeed'	
	
	root :to => 'pages#home'

end

app/models/merchant.rb
class Merchant < ActiveRecord::Base
	belongs_to :city

	has_many :deals

	has_many :merchant_likes, :dependent => :destroy
  has_many :users, :through => :merchant_likes
	
	has_many :merchantcomments, :dependent => :destroy
  has_many :commenters, :class_name => 'User', :through => :merchantcomments
	
	has_attached_file :photo,
    :styles => {
      :thumb=> "75x75#",
      :small  => "400x400>" }
			
	has_attached_file :deal1,
    :styles => {
      :thumb=> "75x75#",
      :small  => "100x100>" }
			
	has_attached_file :deal2,
    :styles => {
      :thumb=> "75x75#",
      :small  => "100x100>" }
			
	has_attached_file :speciality1,
    :styles => {
      :thumb=> "75x75#",
      :small  => "100x100>" }
			
	has_attached_file :speciality2,
    :styles => {
      :thumb=> "75x75#",
      :small  => "100x100>" }

	def merchantliked?(user)#has the current user liked the merchant
		merchant_likes.find_by_user_id(user)
	end
	
	def likeMerchant!(user)
		merchant_likes.create!(:user_id => user.id)
	end
	
	def unlikeMerchant!(user)
		merchant_likes.find_by_user_id(user).destroy
	end
	
	def addComment!(comment)
		merchantcomments.create!(:user_id => comment.user_id, :content => comment.content)
	end
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
	layout 'likesdiary'
	before_filter :is_admin?, :except => [:show, :index]
  def new
		@title = "Create a new Merchant"
		@merchant = Merchant.new
  end

  def index
		@merchants = Merchant.all
  end

  def show
		@merchant = Merchant.find(params[:id])
		@title = @merchant.merchantname
		@likers = @merchant.users
		@comments = @merchant.merchantcomments
		@deals = @merchant.deals
  end

  def edit
		@merchant = Merchant.find(params[:id])
  end
	
	def create 
		@merchant = Merchant.new(params[:merchant])
		if @merchant.save
			redirect_to @merchant
			flash[:success] = 'Merchant was successfully created'
		else
			render :action => :new
		end
	end
	
	def update
		@merchant = Merchant.find(params[:id])
		if @merchant.update_attributes(params[:merchant])
			redirect_to @merchant
			flash[:success] = 'Merchant updated'
		else
			render :action => :edit
		end
	end
	
	def destroy
		@merchant = Merchant.find(params[:id])
		@merchant.destroy
		flash[:success] = 'Merchant deleted'
		redirect_to(merchants_path)
	end
end

app/helpers/merchants_helper.rb
module MerchantsHelper
end

app/views/merchants/_commentsform.html.erb
<%= form_for([@merchant, @merchant.merchantcomments.build]) do |f| %>
  <div class="field">
    <%= f.text_area(:content, :size => "70x5")%>
  </div>
  <div class="actions">
    <%= f.submit "Comment" %>
  </div>
<% end %>

app/views/merchants/_form.erb
<div>
	<%= form.label :photo %>
	<%= form.file_field :photo %>
</div>
<div>
  <%= form.label :merchantname %>
  <%= form.text_field :merchantname %>
</div>
<div>
	<%= form.label :tribecomment %>
	<%= form.text_area :tribecomment %>
</div>
<div>
	<%= form.label :merchantinfo %>
	<%= form.text_area :merchantinfo %>
</div>
<div>
	<%= form.label :meraddress %>
	<%= form.text_area :meraddress %>
</div>
<div>
	<%= form.label :merchantphone %>
	<%= form.text_area :merchantphone %>
</div>
<div>
	<%= form.label :merspectext %>
	<%= form.text_field :merspectext %>
</div>
<div>
	<%= form.label :deal1 %>
	<%= form.file_field :deal1 %>
</div>

<div>
	<%= form.label :deal2 %>
	<%= form.file_field :deal2 %>
</div>

<div>
	<%= form.label :speciality1 %>
	<%= form.file_field :speciality1 %>
</div>

<div>
	<%= form.label :speciality2 %>
	<%= form.file_field :speciality2 %>
</div>

app/views/merchants/_like.html.erb
<% merchant_id = @merchant.id %>
<%= form_for @merchant.merchant_likes.build(:user_id => current_user.id) do |f| %>
<div><%= f.hidden_field :merchant_id %></div>
<div class="actions"><%= f.submit "Like" %></div>
<% end %>

app/views/merchants/_like_form.html.erb
<div>
  <% if @merchant.merchantliked?(current_user) %>
    <%= render 'unlike' %>
  <% else %>
    <%= render 'like' %>
  <% end %>
</div>

app/views/merchants/_merchant.html.erb
<%= merchant.merchantname %>
<% if isadmin? %>
<%= link_to "Edit", edit_merchant_path(merchant) %>
<%= link_to 'Show', merchant %>
<%= link_to 'Destroy', merchant, :confirm => 'Are you sure?', :method => :delete %>
<% end %>
<br/>

app/views/merchants/_unlike.html.erb
<%= form_for @merchant.merchant_likes.find_by_user_id(current_user.id),:html => { :method => :delete } do |f| %>
<div class="actions"><%= f.submit "Unlike" %></div>
<% end %>

app/views/merchants/edit.html.erb
<br/><br/><br/>
<h1>Editing merchant </h1>

<%= form_for @merchant, :html => {:multipart => true} do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <%= render :partial => 'form', :object => f %>
  <%= f.submit "Update merchant!!!" %>
<% end %>

<%= link_to 'Show', @merchant %> |
<%= link_to 'Back', merchants_path %>

app/views/merchants/index.html.erb
Welcome to Likes Diary
<br/><br/>List of all the merchants<br/><br/>

<%= render @merchants %>
<br/><br/>
<% if isadmin? %>
<%= link_to "New Merchant", new_merchant_path %>
<% end %>

app/views/merchants/new.html.erb
<h1>Create a new merchant</h1>

<%= form_for @merchant, :url => merchants_path, :html => {:multipart => true} do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <%= render :partial => 'form', :object => f %>
  <%= f.submit "Create Merchant!!!" %>
<% end %>

app/views/merchants/show.html.erb
<% if isadmin? %>	
	<%= link_to 'Edit', edit_merchant_path %>
<% end %>
<div>
	<div>
		<%= image_tag @merchant.photo.url(:small) %>
	</div>
	<b>Name </b>
	<%= @merchant.merchantname %>	<br/><br/>
	<%= @merchant.merchantinfo %> <br/><br/>
	<%= @merchant.meraddress %> <br/><br/>
	<%= @merchant.merchantphone %> <br/><br/>
	<%= @merchant.merspectext %> <br/><br/>
	<%= @merchant.tribecomment %> <br/><br/>
	<b>City</b><%= @merchant.city.cityname %> <br/><br/>
</div>

	<div>
		<% unless !@merchant.deal1_file_name %>
			<%= image_tag @merchant.deal1.url(:small) %>
		<% end %>
	</div>
	<div>
		<% unless !@merchant.deal2_file_name %>
			<%= image_tag @merchant.deal2.url(:small) %>
		<% end %>
	</div>
	
		<div>
		<% unless !@merchant.speciality1_file_name %>
			<%= image_tag @merchant.speciality1.url(:small) %>
		<% end %>
	</div>
	<div>
		<% unless !@merchant.speciality2_file_name %>
			<%= image_tag @merchant.speciality2.url(:small) %>
		<% end %>
	</div>

Deals offered by this merchant so far<br/>
<%= render @deals %>
<br/><br/><br/><br/>
//add likes here
<%= render 'like_form' if signedin? %>

<br/>

This page has been liked by - <br/>
<%= render @likers %>

//add comments here
<br/>

<% if signedin? %>

	<h2>Comments</h2>
	Count is:
	<%= @merchant.merchantcomments.count %><br/>
	//need to paginate comments later
	<br/><br/>
	<%= render :partial => "merchantcomments/merchantcomment",
           :collection => @comments %>

<% end %>

<br/><br/>

<%= render 'merchants/commentsform' if signedin? %>