config/routes.rb
Likesdiary::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
	
	devise_scope :user do
		get "/login" => "devise/sessions#new"
		get "/logout" => "devise/sessions#destroy"
		get "/register" => "devise/registrations#new"
	end

	match 'products/recentupdate' , :to => 'products#recentupdate'
	match 'products/friendsupdate' , :to => 'products#friendsupdate'
	match 'products/toplist' , :to => 'products#toplist'
	match 'products/commentlist' , :to => 'products#commentlist'
	match 'products/add_image' , :to => 'products#add_image'
	match 'users/likeit' , :to=>'products#likeit'
	
	resources :deals do
		resources :dealcomments
	end
	resources :maingroups
	resources :categories
	resources :subgroups
	resources :ratingcategories
	resources :products do
		resources :associations
		resources :recentupdate
		resources :productcomments, :except => [:index, :show]
		resources :reviews, :except => [:index, :show]
		member do
			get :users
			get :productcomments
			get :reviews
			get :recentupdate			
		end
	end	

	match 'users/followedBy' , :to=> 'users#followedBy'
	
	resources :users do
		member do
			get :following, :followers, :requests ,:requestAct
		end
	end
  resources :user_sessions
	resources :cities
	resources :merchants do
		resources :merchantcomments
	end
	
	resources :relationships, :only => [:create, :destroy]
	resources :ratings, :only => [:create, :update]
	resources :product_likes, :only => [:create, :destroy]
	resources :merchant_likes, :only => [:create, :destroy]
	resources :deal_likes, :only => [:create, :destroy]

  get "user_sessions/new"

  get "users/new"
  
	match '/verify_user', :to => 'pages#verify_user'
	match '/logUser' , :to => 'pages#logUser'
	match '/contact', :to => 'pages#contact'
	match '/about', :to => 'pages#about'
	match 'signup', :to => 'users#new'  
	match 'login' => 'user_sessions#new', :as => :login
	match 'logout' => 'user_sessions#destroy', :as => :logout
	match 'cheapsdiary' => 'deals#currentdeal'
	match 'search' => 'pages#search'
	match 'newsfeed', :to => 'users#newsfeed'	
	
	root :to => 'pages#home'

end

app/models/deal.rb
class Deal < ActiveRecord::Base
	belongs_to :city
	belongs_to :merchant
	
	has_many :deal_likes, :dependent => :destroy
  has_many :users, :through => :deal_likes
	
	has_many :dealcomments, :dependent => :destroy
  has_many :commenters, :class_name => 'User', :through => :dealcomments
	
	has_attached_file :photo,
    :styles => {
      :thumb=> "75x75#",
      :small  => "400x400>" }
	
	validates :name, :presence => true,
									 :length => {:within => 2..50}

	validates :city_id, :presence => true
	
	validates_numericality_of :originalprice
	validates_numericality_of :discount
	validates_numericality_of :maxattenders
	
	def dealliked?(user)#has the current user liked the deal
		deal_likes.find_by_user_id(user)
	end
	
	def likeDeal!(user)
		deal_likes.create!(:user_id => user.id)
	end
	
	def unlikeDeal!(user)
		deal_likes.find_by_user_id(user).destroy
	end
	
	def addComment!(comment)
		dealcomments.create!(:user_id => comment.user_id, :content => comment.content)
	end
	
	default_scope :order => 'created_at DESC'
	scope :citydeals, lambda {|city_id| where(:city_id => city_id) }
	
	def current?
    now = DateTime.now
    startat < now && now < endat
  end
	
	def old?
		now = DateTime.now
		endat < now
	end
	
	def future?
		now = DateTime.now
		startat < now
	end
	
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
	layout 'cheapsdiary'
	before_filter :is_admin?, :only => [:new, :index, :edit, :update, :create, :destroy]
	before_filter :authenticate_user!, :only => [:current_deal]
	
  def new
		@title = "Create a new deal"
		@deal = Deal.new
  end
	
	def create
		@deal = Deal.new(params[:deal])
		if @deal.save
			#add additional checks to see that only a single deal is valid on a day
			redirect_to @deal
			flash[:success] = 'Deal was successfully created'
		else
			render :action => :new
		end
	end
	
	def index
		@deals = Deal.all
	end
	
	def show
		@deal = Deal.find(params[:id])
		@title = @deal.name
		@likers = @deal.users
		@comments = @deal.dealcomments
	end
	
	def edit
		@deal = Deal.find(params[:id])
	end
	
	def update
		@deal = Deal.find(params[:id])
		if @deal.update_attributes(params[:deal])
			redirect_to @deal
			flash[:success] = 'Deal was updated'
		else
			render :action => :edit
		end
	end
	
	def destroy
		@deal = Deal.find(params[:id])
    @deal.destroy
    flash[:success] = "Deal deleted"
    redirect_to(deals_url)
	end
	
	def currentdeal
		@citydeals = Deal.citydeals(current_user.city_id)
		@current
		@old
		@future
		@citydeals.each do |citydeal|
			if citydeal.current?
				@current = citydeal
				return
			end
			if citydeal.old?
				@old = citydeal
				return
			end
			if citydeal.future?
				@future = citydeal
				return
			end
		end
	end

end

app/helpers/deals_helper.rb
module DealsHelper
end

app/views/deals/_commentsform.html.erb
<%= form_for([@deal, @deal.dealcomments.build]) do |f| %>
  <div class="field">
    <%= f.text_area(:content, :size => "70x5")%>
  </div>
  <div class="actions">
    <%= f.submit "Comment" %>
  </div>
<% end %>

app/views/deals/_deal.html.erb
Deal
<%= deal.name %>
<%= link_to "Edit", edit_deal_path(deal) %>
<%= link_to 'Show', deal %>
<%= link_to 'Destroy', deal, :confirm => 'Are you sure?', :method => :delete %>

<br/>

app/views/deals/_form.erb
<div>
  <%= form.label :name %>
  <%= form.text_field :name %>
</div>
<div>
	<%= form.label :city_id %>
	<%= form.collection_select(:city_id, City.all, :id, :cityname) %>
</div>
<div>
	<%= form.label :originalprice %>
	<%= form.text_field :originalprice %>
</div>
<div>
	<%= form.label :discount %>
	<%= form.text_field :discount %>
</div>
<div>
	<%= form.label :maxattenders %>
	<%= form.text_field :maxattenders %>
</div>
<div>
	<%= form.label :info1 %>
	<%= form.text_area :info1 %>
</div>
<div>
	<%= form.label :terms %>
	<%= form.text_area :terms %>
</div>
<div>
	<%= form.label :aboutdeal %>
	<%= form.text_area :aboutdeal %>
</div>
<div>
	<%= form.label :info2 %>
	<%= form.text_area :info2 %>
</div>
<div>
	<%= form.label :address %>
	<%= form.text_area :address %>
</div>

<div>
	<%= form.label :startat %>
	<%= form.datetime_select :startat %>
</div>
<div>
	<%= form.label :endat %>
	<%= form.datetime_select :endat %>
</div>
<div>
	<%= form.file_field :photo %>
</div>
<div>
	<%= form.label :merchant_id %>
	<%= form.collection_select(:merchant_id, Merchant.all, :id, :merchantname) %>
</div>

app/views/deals/_like.html.erb
<% deal_id = @deal.id %>
<%= form_for @deal.deal_likes.build(:user_id => current_user.id) do |f| %>
<div><%= f.hidden_field :deal_id %></div>
<div class="actions"><%= f.submit "Like" %></div>
<% end %>

app/views/deals/_like_form.html.erb
<div>
  <% if @deal.dealliked?(current_user) %>
    <%= render 'unlike' %>
  <% else %>
    <%= render 'like' %>
  <% end %>
</div>

app/views/deals/_unlike.html.erb
<%= form_for @deal.deal_likes.find_by_user_id(current_user.id),:html => { :method => :delete } do |f| %>
<div class="actions"><%= f.submit "Unlike" %></div>
<% end %>

app/views/deals/currentdeal.html.erb
Showing the current deal in the city
<%= current_user.city.cityname %>
<br/><br/>
<p>Active Deals </p>
<% if @currentdeal %>
	<%= @currentdeal.name %>
	show the rest of the details of the current deal
	also options to share and like and comment and attend
<% end %>

app/views/deals/edit.html.erb
<br/><br/><br/>
<h1>Editing deal</h1>

<%= form_for @deal, :html => {:multipart => true} do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <%= render :partial => 'form', :object => f %>
  <%= f.submit "Update Deal!!!" %>
<% end %>

<%= link_to 'Show', @deal %> |
<%= link_to 'Back', deals_path %>

app/views/deals/index.html.erb
Welcome to Likes Diary
<br/><br/>List of all the deals<br/><br/>

<%= render @deals %>
<br/><br/>
<%= link_to "New Deal", new_deal_path %>

app/views/deals/new.html.erb
<h1>Create a new deal </h1>

<%= form_for @deal, :url => deals_path, :html => { :multipart => true } do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <%= render :partial => 'form', :object => f %>
  <%= f.submit "Create Deal!!!" %>
<% end %>

app/views/deals/show.html.erb
<br/><br/><br/>
<% if isadmin? %>	
	<%= link_to 'Edit', edit_deal_path %>
<% end %>

<%= image_tag @deal.photo.url(:small) %>
<b>Name : </b>
<%= @deal.name %><br/><br/>
<b>City</b>
<%= @deal.city.cityname %><br/><br/>
<b>Merchant</b>
<%= link_to @deal.merchant.merchantname, @deal.merchant %><br/><br/>
<b>Original Price </b>
<%= @deal.originalprice %><br/><br/>
<b>Discount</b>
<%= @deal.discount %><br/><br/>
<b>Maxattenders</b>
<%= @deal.maxattenders %><br/><br/>
<b>Info1</b>
<%= @deal.info1 %><br/><br/>
<b>Info2</b>
<%= @deal.info2 %><br/><br/>
<b>Terms</b>
<%= @deal.terms %><br/><br/>
<b>About deal</b>
<%= @deal.aboutdeal %><br/><br/>
<b>Addres</b>
<%= @deal.address %><br/><br/>

<%= @deal.startat %><br/><br/>
<%= @deal.endat %><br/><br/>


//add likes here
<%= render 'like_form' if signedin? %>

<br/>

This page has been liked by - <br/>
<%= render @likers %>



//add comments here
<br/>

<% if signedin? %>

	<h2>Comments</h2>
	Count is:
	<%= @deal.dealcomments.count %><br/>
	//need to paginate comments later
	<br/><br/>
	<%= render :partial => "dealcomments/dealcomment",
           :collection => @comments %>

<% end %>

<br/><br/>

<%= render 'deals/commentsform' if signedin? %>